
package com.d2d.ws.register;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-22T12:55:00.916+05:30
 * Generated source version: 2.7.11
 * 
 */
 
public class IUserRegistration_UserRegistrationPort_Server{

    protected IUserRegistration_UserRegistrationPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IUserRegistrationImpl();
        String address = "http://localhost:8080/Register";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IUserRegistration_UserRegistrationPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
