
package com.d2d.ws.register;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-22T12:57:26.090+05:30
 * Generated source version: 2.7.11
 * 
 */
public final class IUserRegistration_UserRegistrationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://register.ws.d2d.com/", "IUserRegistration");

    private IUserRegistration_UserRegistrationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IUserRegistration_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IUserRegistration_Service ss = new IUserRegistration_Service(wsdlURL, SERVICE_NAME);
        IUserRegistration port = ss.getUserRegistrationPort();  
        
        {
        System.out.println("Invoking registerUser...");
        java.lang.String _registerUser_firstName = "";
        java.lang.String _registerUser_arg1 = "";
        java.lang.String _registerUser_arg2 = "";
        java.lang.String _registerUser__return = port.registerUser(_registerUser_firstName, _registerUser_arg1, _registerUser_arg2);
        System.out.println("registerUser.result=" + _registerUser__return);


        }

        System.exit(0);
    }

}
