package com.d2d.ws.register;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-22T12:57:26.163+05:30
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "IUserRegistration", 
                  wsdlLocation = "file:/D:/java/testservice/src/xml_xsd/ex.wsdl",
                  targetNamespace = "http://register.ws.d2d.com/") 
public class IUserRegistration_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://register.ws.d2d.com/", "IUserRegistration");
    public final static QName UserRegistrationPort = new QName("http://register.ws.d2d.com/", "UserRegistrationPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/testservice/src/xml_xsd/ex.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IUserRegistration_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/testservice/src/xml_xsd/ex.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IUserRegistration_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IUserRegistration_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IUserRegistration_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IUserRegistration_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IUserRegistration_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IUserRegistration_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IUserRegistration
     */
    @WebEndpoint(name = "UserRegistrationPort")
    public IUserRegistration getUserRegistrationPort() {
        return super.getPort(UserRegistrationPort, IUserRegistration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUserRegistration
     */
    @WebEndpoint(name = "UserRegistrationPort")
    public IUserRegistration getUserRegistrationPort(WebServiceFeature... features) {
        return super.getPort(UserRegistrationPort, IUserRegistration.class, features);
    }

}
