package com.d2d.ws.register;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-22T12:57:26.157+05:30
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://register.ws.d2d.com/", name = "IUserRegistration")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserRegistration {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://register.ws.d2d.com/", className = "com.d2d.ws.register.RegisterUser")
    @WebMethod
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://register.ws.d2d.com/", className = "com.d2d.ws.register.RegisterUserResponse")
    public java.lang.String registerUser(
        @WebParam(name = "firstName", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
