
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.d2d.ws.register;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-22T12:57:26.145+05:30
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "IUserRegistration",
                      portName = "UserRegistrationPort",
                      targetNamespace = "http://register.ws.d2d.com/",
                      wsdlLocation = "file:/D:/java/testservice/src/xml_xsd/ex.wsdl",
                      endpointInterface = "com.d2d.ws.register.IUserRegistration")
                      
public class IUserRegistrationImpl implements IUserRegistration {

    private static final Logger LOG = Logger.getLogger(IUserRegistrationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.d2d.ws.register.IUserRegistration#registerUser(java.lang.String  firstName ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String registerUser(java.lang.String firstName,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation registerUser");
        System.out.println(firstName);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
